language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
before_install:
 - sudo apt-get update -qq
install:
    - pip install -rtest-requirements.txt
    - pip install -e ./
script:
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.7.*|3\.[3-4].*) ]]; then pep8 require/; else echo "Skipping PEP8 for $(python --version 2>&1)."; fi
    - if [[ "$(python --version 2>&1)" =~ Python\ (2\.7.*|3\.[3-4].*) ]]; then pyflakes require/; else echo "Skipping PyFlakes for $(python --version 2>&1)."; fi
    - py.test tests/
