#!/usr/bin/python

import argparse
from pypm import actions


parser = argparse.ArgumentParser(
    description="Local Python package management."
)


action_parsers = parser.add_subparsers()

install_parser = action_parsers.add_parser('install')


if __name__ == '__main__':

    args = parser.parse_args()

    actions.install_package_dependencies()
